### ISSUE TITLE
Saving large imported spritesheet as c16 creates extra red pixels

### ISSUE THREAD

**Issue by Vermidia** [zenzoa/spritist#1]
When saving a large sprite(In my case, 101 columns by 1 row, each sprite being 104 x 19) as a c16, at the far right of the colored areas in each sprite , sometimes a red pixel(sometimes a vertical line of red pixels, and in one case, a black line that wasn't transparent) is placed where it didn't exist before.

**Comment by zenzoa** [comment]
Hi! Mind trying again with the latest 2.0 alpha release? Curious if this is still happening

**Comment by Vermidia** [comment]
I don't have the original sprite sheet, but using one with the same size (and probably was the basis), this seems to no longer happen.
