### ISSUE TITLE
2.2 Not Displaying Sprites

### ISSUE THREAD

**Issue by babyblueboxers** [zenzoa/spritist#2]
On Windows 11, opening Spritist, importing images or opening sprite files displays nothing.

![Spritist_zZwWAGPPmZ](https://github.com/zenzoa/spritist/assets/18275780/02bd9458-e870-4841-b594-4d910b752918)

**Comment by zenzoa** [comment]
Thanks for the GIF! I'll take a look in the next few days!

**Comment by zenzoa** [comment]
Fixed in https://github.com/zenzoa/spritist/commit/1fbbfaf0e026b5a3c4f9ae8f61eecb86854e8048
