### ISSUE TITLE
2.2 Spritesheets Columns and Rows have 'px' next to them

### ISSUE THREAD

**Issue by JennaMalkin** [zenzoa/spritist#3]
![Screenshot 2024-10-05 at 6 02 30 pm](https://github.com/user-attachments/assets/00f43b38-b2ec-45da-a652-46830a5e4616)
![Snke(1)_spritesheet](https://github.com/user-attachments/assets/bd2a9b78-3618-45e0-83c3-6b8d799b54f0)

When importing spritesheets, the 'columns' and 'rows' have px next to them, implying that we need to measure by pixels, instead of using these numbers to count the number of images in the spritesheet.  

If and only if you can (this is a low-priority thing), please amend the screen you get when importing spritesheets to not display 'px' beside the columns and rows.

**Comment by zenzoa** [comment]
Fixed in https://github.com/zenzoa/spritist/commit/e48d7dc1913e19165b56eae8f1e829640893b190
